Vagrant.configure("2") do |config|    
    ## immagine di base
    config.vm.box = "debian/bookworm64"
    
    # provider VirtualBox 
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    
    config.vm.define "playground" do |p|
        p.vm.hostname = "playground"
        
        # provsion con ansible 
        p.vm.provision "ansible" do |ansible|
            ansible.playbook = "provision/setup.yaml"
        end
    end
end
