Vagrant.configure("2") do |config|    
    ## immagine di base
    config.vm.box = "debian/bookworm64"
    
    # provider VirtualBox 
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "512"
    end

    ## 1. orchestratore (IP: 192.168.1.7)
    config.vm.define "orchestratore" do |orchestratore|
        orchestratore.vm.hostname = "orchestratore"
        orchestratore.vm.network :private_network, ip: "192.168.1.7" 

        ## provisioning orchestratore 
        orchestratore.vm.provision "shell", path: "provision/orchestratore/setup.sh"
    end

    ## 2. macchina 1 (IP: 192.168.1.5)
    config.vm.define "macchina1" do |macchina1|
        macchina1.vm.hostname = "macchina1.test"
        macchina1.vm.network :private_network, ip: "192.168.1.5" 
        
       ## provisioning della macchina 1
        macchina1.vm.provision "shell", path: "provision/nodi/setup.sh"
    end

    ## 3. macchina 2 (IP: 192.168.1.6)
    config.vm.define "macchina2" do |macchina2|
        macchina2.vm.hostname = "macchina2.test"
        macchina2.vm.network :private_network, ip: "192.168.1.6" 

        ## provisioning della macchina 2
        macchina2.vm.provision "shell",  path: "provision/nodi/setup.sh"
    end
end
