#SPDX-License-Identifier: MIT-0
---
# vars file for install_docker

# pacchetti da rimuovere
rm_packages:
  - podman 
  - buildah 
  - runc 
  - docker 
  - docker-client 
  - docker-client-latest 
  - docker-common 
  - docker-latest 
  - docker-latest-logrotate 
  - docker-logrotate 
  - docker-engine

# pacchetti da installare 
packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io 
  - docker-buildx-plugin 
  - docker-compose-plugin

# docker repo 
docker_repo_baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
docker_repo_gpgkey: "https://download.docker.com/linux/centos/gpg"