Vagrant.configure("2") do |config|    
    ## immagine di base
    config.vm.box = "debian/bookworm64"
    
    # provider VirtualBox 
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
    end
    
    config.vm.define "macchina1" do |m1|
        m1.vm.hostname = "server"
        m1.vm.network :private_network, ip: "192.168.6.67" 
        m1.vm.network "forwarded_port", guest: 80, host: 8080, id: "server"

    end

     config.vm.define "macchina2" do |m2|
        m2.vm.hostname = "client"
        m2.vm.network :private_network, ip: "192.168.6.68" 
        m2.vm.network "forwarded_port", guest: 80, host: 8081, id: "client"

    end
end
